version: 2.1
jobs:
  build:
    working_directory: ~/Stellata.Identity.Api
    machine: true
    steps:
      - checkout
      
      # build image
      - run: |
          docker info
          docker build -t aspnetapp -f ./Stellata.Identity.Api/Dockerfile .
      # deploy the image
      - run: |
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a $HEROKU_APP_NAME